/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.common.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the News service. Represents a row in the &quot;ats_News&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.common.db.model.impl.NewsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.common.db.model.impl.NewsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see News
 * @generated
 */
@ProviderType
public interface NewsModel extends BaseModel<News> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a news model instance should use the {@link News} interface instead.
	 */

	/**
	 * Returns the primary key of this news.
	 *
	 * @return the primary key of this news
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this news.
	 *
	 * @param primaryKey the primary key of this news
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this news.
	 *
	 * @return the uuid of this news
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this news.
	 *
	 * @param uuid the uuid of this news
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this news.
	 *
	 * @return the ID of this news
	 */
	public long getId();

	/**
	 * Sets the ID of this news.
	 *
	 * @param id the ID of this news
	 */
	public void setId(long id);

	/**
	 * Returns the user ID of this news.
	 *
	 * @return the user ID of this news
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this news.
	 *
	 * @param userId the user ID of this news
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this news.
	 *
	 * @return the user uuid of this news
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this news.
	 *
	 * @param userUuid the user uuid of this news
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the title of this news.
	 *
	 * @return the title of this news
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this news.
	 *
	 * @param title the title of this news
	 */
	public void setTitle(String title);

	/**
	 * Returns the sub title of this news.
	 *
	 * @return the sub title of this news
	 */
	@AutoEscape
	public String getSubTitle();

	/**
	 * Sets the sub title of this news.
	 *
	 * @param subTitle the sub title of this news
	 */
	public void setSubTitle(String subTitle);

	/**
	 * Returns the description of this news.
	 *
	 * @return the description of this news
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this news.
	 *
	 * @param description the description of this news
	 */
	public void setDescription(String description);

	/**
	 * Returns the status of this news.
	 *
	 * @return the status of this news
	 */
	public int getStatus();

	/**
	 * Sets the status of this news.
	 *
	 * @param status the status of this news
	 */
	public void setStatus(int status);

	@Override
	public News cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}