/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.student.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Teacher service. Represents a row in the &quot;tr_Teacher&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.student.db.model.impl.TeacherModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.student.db.model.impl.TeacherImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Teacher
 * @generated
 */
@ProviderType
public interface TeacherModel extends BaseModel<Teacher> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a teacher model instance should use the {@link Teacher} interface instead.
	 */

	/**
	 * Returns the primary key of this teacher.
	 *
	 * @return the primary key of this teacher
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this teacher.
	 *
	 * @param primaryKey the primary key of this teacher
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this teacher.
	 *
	 * @return the uuid of this teacher
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this teacher.
	 *
	 * @param uuid the uuid of this teacher
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this teacher.
	 *
	 * @return the ID of this teacher
	 */
	public long getId();

	/**
	 * Sets the ID of this teacher.
	 *
	 * @param id the ID of this teacher
	 */
	public void setId(long id);

	/**
	 * Returns the name of this teacher.
	 *
	 * @return the name of this teacher
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this teacher.
	 *
	 * @param name the name of this teacher
	 */
	public void setName(String name);

	/**
	 * Returns the address of this teacher.
	 *
	 * @return the address of this teacher
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this teacher.
	 *
	 * @param address the address of this teacher
	 */
	public void setAddress(String address);

	@Override
	public Teacher cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}